#!/bin/bash
# 关于 texlive/xelatex 的中文输入
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%只要有相应的字体文档，不需要使用CJKutf8，直接由 xelatex 产生pdf文档	%
#%检索安装字体用命令 fc-list | grep'字体名' 即可知道可用字体		%
#%									%
#\usepackage{fontspec}							%
#\setmainfont[Mapping=tex-text]{LiSu}					%
#%\setmainfont[Mapping=tex-text]{Adobe 宋体 Std}	%article用字体	%
#%\setsansfont[Mapping=tex-text]{Adobe 黑体 Std}	 %Beamer用字体	%
#%									%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

xelatex $1
bibtex $1
xelatex $1
xelatex $1
rm -rf $1.aux $1.bak $1.log $1.bbl $1.blg $1.dvi $1.blg $1.out $1.nav $1.thm $1.snm $1.toc $1.*.xml *.*~ *~ .$1.*.swp *.aux *.bbl *.blg
evince $1.pdf
