LAUNCHPAD_LOC: /share/home/czjiangjun/WORKS/TEST_FireWorks/my_launchpad.yaml
FWORKER_LOC: /share/home/czjiangjun/WORKS/TEST_FireWorks/my_fworker.yaml
QUEUEADAPTER_LOC: /share/home/czjiangjun/WORKS/TEST_FireWorks/my_qadapter.yaml
CONFIG_FILE_DIR: /share/home/czjiangjun/WORKS/TEST_FireWorks
