#!/bin/sh
#PBS -N testjob
#PBS -l nodes1:ppn=4
#PBS -q score
cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
#start creating .machines
echo 'granularity:1' >.machines
echo "lapw0:"`echo $PBS_NODEFILE |cut -d" " -f1` >> .machines
for i in `echo $PBS_NODEFILE`
do
  echo "1:"$i >> .machines
done
echo 'extrafine:1' >>.machines
 echo "------------------------------------------------"
# Run the parallel executable "WIEN2K"
 run_lapw -p -i 10 -ec 0.000001 >out

